version: 2

sources:
  - name: raw_data
    description: Raw taxi trip data from NYC TLC
    database: data-engineering-course-486123
    schema: ny_taxi_dataset
    tables:
      - name: yellow_tripdata
        description: Raw yellow taxi trip records
      - name: green_tripdata
        description: Raw green taxi trip records